### PR TITLE
added support for GET type forms

### PR DESCRIPTION
**Pull request by bancer**

### CODE REVIEW

**Comment by lecterror** [comment]
Hi there, I don't have the time to check this out in detail, does the plugin still pass all the existing tests? If so, we can merge this today, it looks like a clean patch.

**Comment by bancer** [comment]
Hi, yes, all unit tests passed.

**Comment by lecterror** [comment]
Thanks for contributing, this means a lot since my updates have become rare and irregular. Cheers!

**Comment by bancer** [comment]
You're welcome :)

**Pull request merged**
